-- MySQL Script generated by MySQL Workbench
-- Mon Aug  8 10:20:27 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema telovendo_sprint
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `telovendo_sprint` ;

-- -----------------------------------------------------
-- Schema telovendo_sprint
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `telovendo_sprint` DEFAULT CHARACTER SET utf8 ;
USE `telovendo_sprint` ;

-- -----------------------------------------------------
-- Table `telovendo_sprint`.`proveedores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `telovendo_sprint`.`proveedores` ;

CREATE TABLE IF NOT EXISTS `telovendo_sprint`.`proveedores` (
  `idproveedores` INT NOT NULL,
  `representante` VARCHAR(45) NOT NULL,
  `nombre_corporativo` VARCHAR(45) NOT NULL,
  `telefono1` VARCHAR(12) NOT NULL,
  `telefono2` VARCHAR(12) NOT NULL,
  `nombre_atiende` VARCHAR(45) NOT NULL,
  `categoria` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idproveedores`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `telovendo_sprint`.`clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `telovendo_sprint`.`clientes` ;

CREATE TABLE IF NOT EXISTS `telovendo_sprint`.`clientes` (
  `idclientes` INT NOT NULL,
  `nombres` VARCHAR(24) NOT NULL,
  `apellidos` VARCHAR(24) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idclientes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `telovendo_sprint`.`productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `telovendo_sprint`.`productos` ;

CREATE TABLE IF NOT EXISTS `telovendo_sprint`.`productos` (
  `idproductos` INT NOT NULL,
  `precio` INT NOT NULL,
  `categoria` VARCHAR(45) NOT NULL,
  `color` VARCHAR(12) NOT NULL,
  `stock` INT NOT NULL,
  `proveedores_idproveedores` INT NOT NULL,
  PRIMARY KEY (`idproductos`, `proveedores_idproveedores`),
  INDEX `fk_productos_proveedores_idx` (`proveedores_idproveedores` ASC) VISIBLE,
  CONSTRAINT `fk_productos_proveedores`
    FOREIGN KEY (`proveedores_idproveedores`)
    REFERENCES `telovendo_sprint`.`proveedores` (`idproveedores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
